### ISSUE TITLE
Tests needed for hastily written branch.

### ISSUE THREAD

**Issue by Joesalmon1985** [Joesalmon1985/PandemicBoardGame#27]
I've written a new branch

https://github.com/Joesalmon1985/PandemicBoardGame/tree/notest

Which finally has the very barebones of the game, but it's very buggy and has a whole bunch of issues. It needs tests to be written for quite a few of the defs, and the tests that do exist for a lot of the recent ones just aren't robust enough.

**Comment by spethoscope** [comment]
Hey Joe, I'm here with the same sn as Reddit 'spethoscope' 

I don't know sql but I'm crashing through and learning as you are. I'm wondering what your working on. I'm mostly working on iOS with pythonista but I just found out that it does have sqlite3 so bear with me I'm learning

**Comment by Joesalmon1985** [comment]
No pressure, the main thing SQLite3 is used for is for creating and
updating a .db file called pandemic which has the game info stored across a
selection of tables. The only commands used are

DROP - to delete tables from prior runnings of the game
CREATE - to make tables
INSERT - to add values into the tables
UPDATE - to change values in the tables
SELECT - grab data from the tables to use in python

I think anyhow. I'm not sure it was the most efficient way to do this to be
honest, and maybe pure python would have worked better.

Hopefully the readme.md file gives enough of a guide as to what I've done
so far, but let me know if anything just doens't make sense

Thanks again for your help

With hope
Joe

**Comment by Joesalmon1985** [comment]
Just to elaborate on what needs doing at the start of this project I tried to work along the lines of 

1 - decide what I needed a def to do
2 - write a test to check that the def had worked
3 - write the def

However as things have gone on I've written quite a few defs, and whole classes that don't have tests.

If you run the tests for the makeboard class and inaturn class by using the command
Python -m unittest t_makeboard 
or
Python -m unittest t_inaturn

You can see that the makeboard class has a whole bunch of rather robust tests which checks all the defs in the class work. 

However the inaturn class needs a few more tests to be written for it. I've also written 2 new classes which have no tests at all. This is probably the most urgent work that needs doing.

**Comment by Joesalmon1985** [comment]
I've finally created a VERY ropey text only version of the game which can be played by running the game.py file with python.

It's full of bugs, I think the next step is to identify what these are, tests to see if they are still present then eliminate them.
